### ISSUE TITLE
Send set_meta requests to Lizard API v4 instead of v3

### ISSUE THREAD

**Issue by lexvand** [nens/raster-feeder#26]
Lizard API v3 is deprecated. We should use v4 instead. In access logging I ran into requests by the sa_raster_feeder account to the set_meta endpoints of rasters that are fed. This needs to be changed before May 2023 in order to keep the service up.

**Comment by arjanverkerk** [comment]
I think there is currently no v4 alternative. It will not take much time to create one, but we can see if raster service  development goes fast enough to replace the current workflow.

**Comment by arjanverkerk** [comment]
Done: v3 set_meta => v4 refresh.
